version: "2"

run:
  timeout: 5m

linters:
  default: none
  enable:
    - govet
    - revive
    - staticcheck
    - unused
    - ineffassign
    - unconvert
    - gocritic
    - gosec
    - dupl
    - misspell
    - nakedret
    - prealloc
    - gochecknoinits
  settings:
    govet:
      enable:
        - shadow
    goconst:
      min-len: 2
      min-occurrences: 2
    misspell:
      locale: US
    lll:
      line-length: 140
    gocritic:
      enabled-tags:
        - performance
        - style
        - experimental
      disabled-checks:
        - wrapperFunc
        - hugeParam
        - rangeValCopy
        - singleCaseSwitch
        - ifElseChain
  exclusions:
    generated: lax
    paths:
      - vendor
    rules:
      - linters:
          - revive
        text: "package-comments: should have a package comment"
      - linters:
          - staticcheck
        text: "at least one file in a package should have a package comment"
      - linters:
          - gosec
          - dupl
        path: _test\.go$
